use_frameworks!
platform :ios, '13.0'

target 'OSSSpeechKit_Example' do
  pod 'OSSSpeechKit', :path => '../'
  pod 'PureLayout', :inhibit_warnings => true
  
  target 'OSSSpeechKit_Tests' do
    inherit! :search_paths

    
  end
end
