# Check Travis CI version info:
# https://docs.travis-ci.com/user/reference/osx/
language: objective-c
osx_image: xcode11.3
xcode_workspace: OSSSpeechKit.xcworkspace
xcode_scheme: OSSSpeechKit-Example
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 11
before_install:
- cd Example
- pod install
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - gem install jazzy
  - make documentation
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: docs
  on:
    branch: master
