language: swift
osx_image: xcode10.2.1
xcode_project: Example/OSSSpeechKit.xcworkspace
xcode_scheme: Example/OSSSpeechKitTests
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
podfile: Example/Podfile
after_success:
  - bash <(curl -s https://codecov.io/bash)