language: objective-c
osx_image: xcode10.2
xcode_workspace: OSSSpeechKit.xcworkspace
xcode_scheme: OSSSpeechKit
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
# podfile: Example/Podfile
before_install:
- cd Example
- pod install
after_success:
  - bash <(curl -s https://codecov.io/bash)