# Check Travis CI version info:
# https://docs.travis-ci.com/user/reference/osx/
language: objective-c
osx_image: xcode11.6
xcode_workspace: OSSSpeechKit.xcworkspace
xcode_scheme: OSSSpeechKit-Example
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
before_install:
- cd Example
- pod install
after_success:
#  - bash <(curl -s https://codecov.io/bash)
# Fixing code cov issue with solution from https://community.codecov.io/t/llvm-cov-failed-to-produce-results-for/1652/9
  - bash <(curl https://codecov.io/bash | sed 's/"$beta_xcode_partials"//g')
  - gem install jazzy
  - make documentation
# deploy:
#   provider: pages
#   cleanup: false
#   github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
#   local-dir: docs
#   on:
#     branch: master
