language: swift
os: osx
osx_image: xcode10
script:
  - xcodebuild -scheme OSSSpeechKit -workspace OSSSpeechKit.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.2' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)