name: Swift PM

on:
  pull_request:
    types:
      - reopened
      - opened
      - synchronize

jobs:
  swift-pm:

    runs-on: 'macos-12'

    steps:
    - uses: actions/checkout@master

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test --parallel -v
