name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: |
        cd Example
        pod install
        xcodebuild test -workspace *.xcworkspace -scheme OSSSpeechKit -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11 Pro Max' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        bash <(curl https://codecov.io/bash | sed 's/"$beta_xcode_partials"//g')
