name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Run
      run: |
        cd Example
        pod install
        swift build -v
        swift test -v
        bash <(curl https://codecov.io/bash | sed 's/"$beta_xcode_partials"//g')
