name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Open Example
      run: cd ../../../Example/
    - name: Where are we
      run: echo pwd
    - name: Install Pods
      run: pod install
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Upload code cov
      run: bash <(curl https://codecov.io/bash | sed 's/"$beta_xcode_partials"//g')
